"""add soft delete fields to AudioFile

Revision ID: 2ba58d239dab
Revises: 592348364ac5
Create Date: 2025-08-06 00:03:46.631711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba58d239dab'
down_revision: Union[str, Sequence[str], None] = '592348364ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('in_bin', sa.Boolean(), nullable=True))
    op.add_column('audio_files', sa.Column('time_of_throwing_to_bin', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('audio_files', 'time_of_throwing_to_bin')
    op.drop_column('audio_files', 'in_bin')
    # ### end Alembic commands ###
