"""switch UUID to String in AudioFile.id

Revision ID: 592348364ac5
Revises: 4c937acd574d
Create Date: 2025-08-05 23:55:58.835058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592348364ac5'
down_revision: Union[str, Sequence[str], None] = '4c937acd574d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
